name: Pre-Release
on:
  release:
    types:
      - prereleased
jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: publish --dry-run --token ${{ secrets.CARGO_REGISTRY_TOKEN }}